### ISSUE TITLE
Needle 2.0.0

### ISSUE THREAD

**Issue by MitraDarja** [seqan/needle#124]
- [ ] Add HIBF  #100 
- [ ] Add Merge option #38
- [ ] Add update option? #38
- [ ] Make Preprocessing better with multiple threads
- [ ] Make count competitive with kallisto & Co.?
- [ ] Add argument verbose #32
